x-linux-container-environment: &common-linux-container-environment-variables
  TZ: ${TZ}
  APP_UID: ${APP_UID:-1000}
  APP_GID: ${APP_GID:-1000}

x-gin-app-environment: &common-gin-app-environment-variables
  TZ: ${TZ}
  APPLICATION_ENVIRONMENT: ${APPLICATION_ENVIRONMENT}
    # 1000 is the default main user uid/gid, using it as a sane default value
  APP_UID: ${APP_UID:-1000}
  APP_GID: ${APP_GID:-1000}
  API_PORT: ${API_PORT}
  API_PORT_INTERNAL: ${API_PORT_INTERNAL}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  SECRET_KEY: ${SECRET_KEY}

services:

  # Gin application
  fintrace-api:
    image: "fintrace-api:latest"
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT_INTERNAL}
    env_file:
      - .env
    volumes:
      - ./backend/:/app
    depends_on:
      - fintrace-db
    restart: unless-stopped


  # Postgres database, data is persisted in a volume
  fintrace-db:
    image: "postgres:14.5-alpine"
    environment:
      <<: *common-linux-container-environment-variables
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT_INTERNAL}
    volumes:
      - fintrace-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  fintrace-db-data:
    name: ${POSTGRES_STORAGE_VOLUME_NAME}
